parameters:
  sonata.user.admin.groupname: 'Users'
  
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ItoSoftware\Components\ModelBundle\Entity\User
    group:
        group_class:  ItoSoftware\Components\ModelBundle\Entity\Group
        
        

sonata_user:
    security_acl:           false

    manager_type: orm # Can be orm for mongodb

    table:
        user_group: "fos_user_user_group"

    impersonating:
        route:                page_slug
        parameters:           { path: / }

    class:                  # Entity Classes
        user:               ItoSoftware\Components\ModelBundle\Entity\User
        group:              ItoSoftware\Components\ModelBundle\Entity\Group

    admin:                  # Admin Classes
        user:
            class:          ItoSoftware\Components\AdminBundle\Admin\ItoUserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
#
#        group:
#            class:          ItoSoftware\Components\AdminBundle\Admin\ItoGroupAdmin
#            controller:     SonataAdminBundle:CRUD
#            translation:    SonataUserBundle

    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]