
front_frontend:
    resource: "@FrontFrontendBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults:  { _locale: en }
    requirements:
        _locale: en|es|fr|

#ito_model:
#    resource: "@ItoModelBundle/Resources/config/routing.yml"
#    prefix:   /

#ito_user:
#    resource: "@ItoUserBundle/Resources/config/routing.yml"
#    prefix:   /ito-software/base/

ito_admin:
    resource: "@ItoAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/{_locale}
    defaults:  { _locale: en }
    requirements:
        _locale: en|es|fr|
        
redirect_admin:
    pattern:  /admin
    defaults: { _controller: ItoAdminBundle:Default:redirectAdmin }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user_profile_show:
    pattern:  /user/password-recovery
    defaults: { _controller: ItoUserBundle:Default:passwordRecovery }

    
sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin/{_locale}
    defaults:  { _locale: en }
    requirements:
        _locale: en|es|fr|
  
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin/{_locale}
  
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

    
    
 
    
  
