
front_frontend:
    resource: "@FrontFrontendBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    defaults:  { _locale: en }
    requirements:
        _locale: en|es|fr|

#ito_model:
#    resource: "@ItoModelBundle/Resources/config/routing.yml"
#    prefix:   /

#ito_user:
#    resource: "@ItoUserBundle/Resources/config/routing.yml"
#    prefix:   /ito-software/base/

ito_admin:
    resource: "@ItoAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/{_locale}
    defaults:  { _locale: en }
    requirements:
        _locale: en|es|fr|
        
redirect_admin:
    pattern:  /admin
    defaults: { _controller: ItoAdminBundle:Default:redirectAdmin }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user_profile_show:
    pattern:  /user/password-recovery
    defaults: { _controller: ItoUserBundle:Default:passwordRecovery }

    
sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin/{_locale}
    defaults:  { _locale: en }
    requirements:
        _locale: en|es|fr|
  
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin/{_locale}
  
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth:
    resource_owners:
        any_name:
            type:                facebook
            client_id:           406153069523025
            client_secret:       929ad8d54a9b24aabbd9e8958151a0eb
            
            


hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: secured_area

    # an optional setting to configure a query string parameter which can be used to redirect
    # the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
    # redirect the user to /my/destination after facebook authenticates them.  If this is not
    # set then the user will be redirected to the original resource that they requested, or
    # the base address if no resource was requested.  This is similar to the behaviour of
    # [target_path_parameter for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html).
    # target_path_parameter: _destination

    # an optional setting to use the HTTP REFERER header to be used in case no
    # previous URL was stored in the session (i.e. no resource was requested).
    # This is similar to the behaviour of
    # [using the referring URL for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html#using-the-referring-url).
    # use_referer: true

    # here you will add one (or more) configurations for resource owners
    # and other settings you want to adjust in this bundle, just checkout the list below!
    
    
 
    
  
