
  
services: 
    my.oauth_aware.user_provider.service:
        class: ItoSoftware\Components\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments:
            userManager: "@fos_user.user_manager"
            properties:  {facebook: facebookid} 

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
      
    
            
     