servicio:
  pattern:   /
  defaults:  { _controller: "ItoApiBundle:Activity:index"}
  requirements:
    _method:  GET
    
servicio_show:
  pattern:   /{id}
  defaults:  { _controller: "ItoApiBundle:Activity:show"}
  requirements:
      _method:  GET
      id: \d+