categoria_lugar:
    pattern:  /
    defaults: { _controller: "CiturApiBundle:CategoriaLugar:index" }
    requirements:
        _method: GET
        
categoria_lugar_show:
    pattern:  /{id}
    defaults: { _controller: "CiturApiBundle:CategoriaLugar:show" }
    requirements:
        _method: GET
        id: "\d+"