destino:
  pattern:   /
  defaults:  { _controller: "CiturApiBundle:Destino:index"}
  requirements:
    _method:  GET
    
destino_show:
  pattern:   /{id}
  defaults:  { _controller: "CiturApiBundle:Destino:show"}
  requirements:
      _method:  GET
      id: \d+