servicio_galeria:
    pattern:  /
    defaults: { _controller: "CiturApiBundle:ServicioGaleria:index"}
    requirements:
        _method: GET

servicio_galeria_show:
   pattern:   /{id}
   defaults:  { _controller: "CiturApiBundle:ServicioGaleria:show"}
   requirements:
      _method: GET
      id:      \d+