<?php

namespace Proxies\__CG__\ItoSoftware\Components\ModelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activity extends \ItoSoftware\Components\ModelBundle\Entity\Activity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'name', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'description', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'registredDate', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'active', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'cost', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'id', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'galery', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'plan', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'places', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'costa');
        }

        return array('__isInitialized__', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'name', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'description', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'registredDate', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'active', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'cost', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'id', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'galery', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'plan', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'places', '' . "\0" . 'ItoSoftware\\Components\\ModelBundle\\Entity\\Activity' . "\0" . 'costa');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Activity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getGaleryLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGaleryLength', array());

        return parent::getGaleryLength();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistredDate($registredDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistredDate', array($registredDate));

        return parent::setRegistredDate($registredDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistredDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistredDate', array());

        return parent::getRegistredDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setCost($cost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCost', array($cost));

        return parent::setCost($cost);
    }

    /**
     * {@inheritDoc}
     */
    public function getCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCost', array());

        return parent::getCost();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addGalery(\ItoSoftware\Components\ModelBundle\Entity\Galery $galery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGalery', array($galery));

        return parent::addGalery($galery);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGalery(\ItoSoftware\Components\ModelBundle\Entity\Galery $galery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGalery', array($galery));

        return parent::removeGalery($galery);
    }

    /**
     * {@inheritDoc}
     */
    public function getGalery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGalery', array());

        return parent::getGalery();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlan(\ItoSoftware\Components\ModelBundle\Entity\Plan $plan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlan', array($plan));

        return parent::addPlan($plan);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlan(\ItoSoftware\Components\ModelBundle\Entity\Plan $plan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlan', array($plan));

        return parent::removePlan($plan);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlan', array());

        return parent::getPlan();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlace(\ItoSoftware\Components\ModelBundle\Entity\Places $places)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlace', array($places));

        return parent::addPlace($places);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlace(\ItoSoftware\Components\ModelBundle\Entity\Places $places)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlace', array($places));

        return parent::removePlace($places);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaces', array());

        return parent::getPlaces();
    }

    /**
     * {@inheritDoc}
     */
    public function setCosta($costa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCosta', array($costa));

        return parent::setCosta($costa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCosta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosta', array());

        return parent::getCosta();
    }

}
