parameters:
#    ito_admin.example.class: ItoSoftware\Base\AdminBundle\Example

services:
#    ito_admin.example:
#        class: %ito_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

   sonata.user.admin.user:
       class: ItoSoftware\Base\AdminBundle\Admin\ItoUserAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: '%sonata.user.admin.groupname%', label: 'users',   label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
       arguments:
           - null
           - %sonata.user.admin.user.entity%
           - %sonata.user.admin.user.controller%
       calls:
            - [setUserManager, ["@fos_user.user_manager"]]
            - [setTranslationDomain, [%sonata_user.admin.user.translation%, ItoAdminBundle]]
            
services:
 sonata.activity.admin.activity:
       class: ItoSoftware\Base\AdminBundle\Admin\ActivityAdmin
       tags:
         - { name: sonata.admin, manager_type: orm, group: group, label: 'activities' ,   label_translator_strategy: 'sonata.admin.label.strategy.underscore'}
       arguments: [null, ItoSoftware\Base\ModelBundle\Entity\Activity, ItoAdminBundle:ActivityAdmin] 